# Big Data Project: Transforming Scientific Articles into Videos with Speech using Apache Spark and Kafka

In [ ]:
# make modules from py files auto-reload when changed
%load_ext autoreload
%autoreload 2

# TTS

## Basic run just for test

In [3]:
import torch
from datetime import datetime
from ArticleReader.Chunker import Chunker
from ArticleReader.LatexToSpeech import LatexParser
from ArticleReader.Narrator import Narrator
from Benchmarking import Bench
import pandas as pd 
import json

/media/michael/Data/anaconda3/envs/TTS/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []

ImportError: cannot import name 'Bench' from 'Benchmarking' (/home/michael/Projects/ArticleReader/Benchmarking/__init__.py)

In [ ]:
input_file = "data/arXiv-2106.04624v1/main.tex"
output_file = "output/" + datetime.now().strftime(r"%y.%m.%d-%H")

parser = LatexParser()
content = parser.read_latex(input_file)
processed = parser.custom_latex_to_text(content)
parser.save_text(processed, "dbg/spec_my.txt")

tables = parser.get_tables()
parser.save_text(tables, "dbg/tables.tex")

In [ ]:
chunker = Chunker(max_len=200)
chunker.split_text_into_chunks(processed)
chunks = chunker.get_test_batch(10, 0)
# chunks = chunker.chunks
chunker.save_chunks_as_text(output_file + ".md", chunks)
print("text chunks:", [len(ch) for ch in chunks])

In [ ]:

narrator = Narrator()

In [ ]:
# break
# waveforms, durations = narrator.text_to_speech_batched(chunks)
# durations_sec = durations / 22050.0

# print("durations: ", durations_sec)

# waveform = torch.cat(waveforms, dim=1)

# print("saving audio")
# narrator.save_audio(output_file + ".wav", waveform)

# narrator.save_video(output_file)

# narrator.generate_srt(chunks, durations_sec, output_file + ".srt")

## Run batch from sorted

In [ ]:
batch_from_sorted = chunker.get_batch_sorted(batch_size=100, start=0)

In [ ]:
batch_from_sorted

In [ ]:
#batch_converted = narrator.text_to_speech_df(batch_from_sorted)

In [ ]:
batch_converted.columns

In [ ]:
batch_converted

In [ ]:
# restore order of sentences
batch_converted.sort_values("index", ascending=True, inplace=True)
# recombine and save sound
waveform = torch.cat(tuple(batch_converted.waveform), dim=1)

In [ ]:
print("saving batch")
narrator.save_audio(output_file + ".wav", waveform)
chunker.save_chunks_as_text(output_file + ".md", batch_converted.sentence)

In [ ]:
[print(s) for s in batch_converted.sentence]

## TTS benchmarking
Benchmarking batch sizes - how they impact memory utilization

#### Experiment report v.1  
schema of the json file   
```
variables: 
    device(CPU/GPU) 
    tts_model (tacotron, fastspeech,...)
    vocoder_model (hifigan, ...)
    batch_size (1,2,3, 5, 10, 20, 30, 50, 70, 100, 200)
    chunk_length (50 : 50 : 500)
parameters: 
    time 
    experiment_id 
    chunk_duration 
    avg_percent_silence     
    tts_model:
        model_id (name)
        max_memory_use 
        run_time 
        memory_log []
        exceptions 
        n_threads?
    vocoder_model:
        model_id (name)
        max_memory_use 
        run_time 
        memory_log []
        exceptions 
        n_threads?
```

#### Experiment report v.2 
schema of the json file   
```

    #variables: 
device(CPU/GPU) 
tts_model (tacotron, fastspeech,...)
vocoder_model (hifigan, ...)
batch_size (1,2,3, 5, 10, 20, 30, 50, 70, 100, 200)
chunk_length (50 : 50 : 500)

    #parameters: 
time 
experiment_id
stage: (tts/vocoder)
chunk_durations 
avg_percent_silence
max_memory_use 
run_time 
memory_log []
exceptions 
n_threads?

```

### Gather benchmark data

In [ ]:

bench = Bench()

In [ ]:
case = {"chunk_length": 50, # (50 : 50 : 500)
     "batch_size": 2, # (1, 2, 3, 5, 10, 20, 30, 50, 70, 100, 200)        
     "tts_model": "tts-tacotron2-ljspeech",
     "vocoder_model": "tts-hifigan-ljspeech",
     "device": "CPU", 
       }
case

In [ ]:
# experiment_run = bench.run_experiment(processed, case)
# with open("benchmark/" + experiment_run[0]["experiment_id"] + ".json", "w+") as f:
#     json.dump(experiment_run,f)
# print('done')

In [ ]:
#experiment_run

## Multiple experiments run

In [ ]:
import torch
from datetime import datetime
from ArticleReader.Chunker import Chunker
from ArticleReader.LatexToSpeech import LatexParser
from ArticleReader.Narrator import Narrator
from Benchmarking import Bench
import pandas as pd 
import json

In [ ]:
input_file = "data/arXiv-2106.04624v1/main.tex"
output_file = "output/" + datetime.now().strftime(r"%y.%m.%d-%H")

parser = LatexParser()
content = parser.read_latex(input_file)
processed = parser.custom_latex_to_text(content)
parser.save_text(processed, "dbg/spec_my.txt")
 
tables = parser.get_tables()
parser.save_text(tables, "dbg/tables.tex")

In [ ]:
smallgrid = {"chunk_length": [75,100],
             "batch_size": (2, 3),
             "tts_model": ["tts-tacotron2-ljspeech"],
             "vocoder_model": ["tts-hifigan-ljspeech"],
             "device": ["CPU"], 
       }
smallgrid

In [ ]:
bench = Bench()
bench.run_experiments(processed, smallgrid, 1)

In [ ]:
largegrid = {"chunk_length": [1000],
             "batch_size": (100, 2),
             "tts_model": ["tts-tacotron2-ljspeech"],
             "vocoder_model": ["tts-hifigan-ljspeech"],
             "device": ["CPU"],
            }
largegrid

In [ ]:

bench = Bench()
bench.run_experiments(processed, largegrid)

In [ ]:
1270546432 /  1.074e+9

In [ ]:
fullgrid = {"chunk_length": list(range(50, 1500, 135)),
             "batch_size": (1, 3, 5, 10, 20, 50, 70, 100, 125, 150, 200, 300),
             "tts_model": ["tts-tacotron2-ljspeech", ],
             "vocoder_model": ["tts-hifigan-ljspeech"],
             "device": ["CPU"], 
       }
fullgrid

In [ ]:
print("grid sizes:")
print("-"*20)
cases = 1
for k,v in fullgrid.items():
    cases = cases*len(v)
    print(k, ":", len(v))
print("-"*20)
print("total cases: ", cases)

In [ ]:
bench = Bench()
bench.run_experiments(processed, fullgrid)

In [ ]:
cases = bench.permutations(grid)

with open("cases.json", 'w+') as f:
    json.dump(cases, f, indent=4)

In [ ]:
bnch_data.columns

In [ ]:
type(experiment_run["parameters"]["tts_model"]["memory_log"]["time"][0])

### Examine individual memory logs

In [ ]:
log = pd.DataFrame(narrator.profilers['vocoder'].memory_log,)
log['time'] = pd.to_datetime(log[0], unit='s')

In [ ]:
log.plot(x='time', y=1)

In [ ]:
log.shape

In [ ]:
torch.torch_version.internal_version

# Grid spanning

In [1]:
import pandas as pd 
import json
import jq

In [16]:
grid = {
        "meta.device": ["GPU"], 
        "model.name": ["tts-tacotron2-ljspeech"],
        #"vocoder_model": ["tts-hifigan-ljspeech"],
        "meta.chunk_length": range(50, 500, 50),
        "meta.batch_size": (1, 2, 3, 5, 10, 20, 30, 50, 70, 100, 200),
    }

In [17]:
list(range(50, 500, 50))

[50, 100, 150, 200, 250, 300, 350, 400, 450]

In [18]:
grid

{'meta.device': ['GPU'],
 'model.name': ['tts-tacotron2-ljspeech'],
 'meta.chunk_length': range(50, 500, 50),
 'meta.batch_size': (1, 2, 3, 5, 10, 20, 30, 50, 70, 100, 200)}

In [19]:
fl = "/home/michael/Projects/ArticleReader/Benchmarking/config/ArticleReader.json"
with open(fl, 'r') as f:
    templ = json.load(f)

templ.pop('summary')
templ.pop('progress')
# templ.pop('data')
# templ.pop('model')
templ

{'meta': {'stage': 'tts',
  'memory_limit_bytes': 26281478400.0,
  'device': 'CPU',
  'chunk_length': 320,
  'batch_size': 125},
 'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
 'model': {'name': 'tts-tacotron2-ljspeech',
  'class': 'Tacotron2',
  'provider': 'speechbrain',
  'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
  'overrides': {'max_decoder_steps': 2000}}}

In [20]:
from Benchmarking.utils import permutations

cases = permutations(grid)
cases

[{'meta.batch_size': 1,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'}]

In [21]:
len(cases)

99

In [22]:
a = "r h t i".split(" ")
b = "1 2 3".split(" ")
c = "x y".split(" ")
dr = {"a": a, "b":b , "c": c }
dr

{'a': ['r', 'h', 't', 'i'], 'b': ['1', '2', '3'], 'c': ['x', 'y']}

In [23]:
permutations(dr)

[{'c': 'x', 'b': '1', 'a': 'r'},
 {'c': 'y', 'b': '1', 'a': 'r'},
 {'c': 'x', 'b': '2', 'a': 'r'},
 {'c': 'y', 'b': '2', 'a': 'r'},
 {'c': 'x', 'b': '3', 'a': 'r'},
 {'c': 'y', 'b': '3', 'a': 'r'},
 {'c': 'x', 'b': '1', 'a': 'h'},
 {'c': 'y', 'b': '1', 'a': 'h'},
 {'c': 'x', 'b': '2', 'a': 'h'},
 {'c': 'y', 'b': '2', 'a': 'h'},
 {'c': 'x', 'b': '3', 'a': 'h'},
 {'c': 'y', 'b': '3', 'a': 'h'},
 {'c': 'x', 'b': '1', 'a': 't'},
 {'c': 'y', 'b': '1', 'a': 't'},
 {'c': 'x', 'b': '2', 'a': 't'},
 {'c': 'y', 'b': '2', 'a': 't'},
 {'c': 'x', 'b': '3', 'a': 't'},
 {'c': 'y', 'b': '3', 'a': 't'},
 {'c': 'x', 'b': '1', 'a': 'i'},
 {'c': 'y', 'b': '1', 'a': 'i'},
 {'c': 'x', 'b': '2', 'a': 'i'},
 {'c': 'y', 'b': '2', 'a': 'i'},
 {'c': 'x', 'b': '3', 'a': 'i'},
 {'c': 'y', 'b': '3', 'a': 'i'}]

In [24]:
cases

[{'meta.batch_size': 1,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 50,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 100,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 150,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 200,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 250,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 300,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 350,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 400,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 1,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 2,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 3,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 5,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 10,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 20,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 30,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 50,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 70,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 100,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'},
 {'meta.batch_size': 200,
  'meta.chunk_length': 450,
  'model.name': 'tts-tacotron2-ljspeech',
  'meta.device': 'GPU'}]

In [25]:
pd.DataFrame(cases)

    meta.batch_size  meta.chunk_length              model.name meta.device
0                 1                 50  tts-tacotron2-ljspeech         GPU
1                 2                 50  tts-tacotron2-ljspeech         GPU
2                 3                 50  tts-tacotron2-ljspeech         GPU
3                 5                 50  tts-tacotron2-ljspeech         GPU
4                10                 50  tts-tacotron2-ljspeech         GPU
..              ...                ...                     ...         ...
94               30                450  tts-tacotron2-ljspeech         GPU
95               50                450  tts-tacotron2-ljspeech         GPU
96               70                450  tts-tacotron2-ljspeech         GPU
97              100                450  tts-tacotron2-ljspeech         GPU
98              200                450  tts-tacotron2-ljspeech         GPU

[99 rows x 4 columns]

In [26]:
## jq query to update value at path meta.device 


def upd_path(pth, val, templ):
    if jq.compile(f'.{pth}?').input(templ).first():
        jqquery = f'.{pth} = "{val}"'
        templ = jq.compile(jqquery).input(templ).first() 
        #print(f"set {k} to {o}")
        return templ
    else:
        print(f"key {pth} not in template")
        raise KeyError(pth)

pth = "meta.chunk_length"

wat = upd_path(pth, '344' , templ)
# print(len(wat))
wat

{'meta': {'stage': 'tts',
  'memory_limit_bytes': 26281478400,
  'device': 'CPU',
  'chunk_length': '344',
  'batch_size': 125},
 'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
 'model': {'name': 'tts-tacotron2-ljspeech',
  'class': 'Tacotron2',
  'provider': 'speechbrain',
  'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
  'overrides': {'max_decoder_steps': 2000}}}

In [29]:

def span_grid(grid, templ):
    cases = []
    for caSe in permutations(grid):
        t = templ.copy()
        for k,v in caSe.items():
            t = upd_path(k, v, t)
        cases.append(t) 
    return cases

new_templ = span_grid(grid, templ)

print(len(new_templ))

99

In [30]:

new_templ

[{'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '1'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '2'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '3'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '5'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '10'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '20'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '30'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '50'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '70'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '100'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '50',
   'batch_size': '200'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '1'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '2'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '3'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '5'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '10'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '20'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '30'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '50'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '70'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '100'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '100',
   'batch_size': '200'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '1'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '2'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '3'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '5'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '10'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '20'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '30'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '50'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '70'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '100'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '150',
   'batch_size': '200'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '1'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '2'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '3'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '5'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '10'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '20'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '30'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '50'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '70'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '100'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '200',
   'batch_size': '200'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '250',
   'batch_size': '1'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '250',
   'batch_size': '2'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '250',
   'batch_size': '3'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '250',
   'batch_size': '5'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '250',
   'batch_size': '10'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',
   'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
   'overrides': {'max_decoder_steps': 2000}}},
 {'meta': {'stage': 'tts',
   'memory_limit_bytes': 26281478400,
   'device': 'GPU',
   'chunk_length': '250',
   'batch_size': '20'},
  'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
  'model': {'name': 'tts-tacotron2-ljspeech',
   'class': 'Tacotron2',
   'provider': 'speechbrain',

In [31]:
pd.DataFrame(new_templ)

,meta,data,model
0,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
1,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
2,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
3,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
4,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
...,...,...,...
94,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
95,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
96,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
97,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."
98,"{'stage': 'tts', 'memory_limit_bytes': 2628147...",{'test_data': 'data/arXiv-2106.04624v1/main.tex'},"{'name': 'tts-tacotron2-ljspeech', 'class': 'T..."

In [28]:
new_templ = jq.compile(jqquery).input(templ).first()

In [29]:
new_templ

{'meta': {'stage': 'tts',
  'memory_limit_bytes': 26281478400,
  'device': 'PPU',
  'chunk_length': 320,
  'batch_size': 125},
 'summary': {'time': '25.02.23-03.02.47',
  'max_memory_use': 3931697152,
  'run_time_sec': 196.09138,
  'avg_percent_silence': 0.2063680000000001,
  'exceptions': None,
  'n_threads': None,
  'experiment_id': '25.02.23-03.02.47'},
 'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
 'model': {'name': 'tts-tacotron2-ljspeech',
  'class': 'Tacotron2',
  'provider': 'speechbrain',
  'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
  'overrides': {'max_decoder_steps': 2000}},
 'progress': [{'unit': 'sample',
   'i': 3826,
   'samplerate': '1/second',
   'start': 1740272567.8687654,
   'resources': {'rss_mb': 4602.8671875,
    'size_bytes': 113936,
    'vms_mb': 15286988800,
    'processes': 1,
    'num_threads': 76,
    'per_process_limit': 26281478400,
    'free_memory': 21822556000}}]}

In [11]:
templ

{'meta': {'stage': 'tts',
  'memory_limit_bytes': 26281478400.0,
  'device': 'CPU',
  'chunk_length': 320,
  'batch_size': 125},
 'summary': {'time': '25.02.23-03.02.47',
  'max_memory_use': 3931697152.0,
  'run_time_sec': 196.09138,
  'avg_percent_silence': 0.2063680000000001,
  'exceptions': None,
  'n_threads': None,
  'experiment_id': '25.02.23-03.02.47'},
 'data': {'test_data': 'data/arXiv-2106.04624v1/main.tex'},
 'model': {'name': 'tts-tacotron2-ljspeech',
  'class': 'Tacotron2',
  'provider': 'speechbrain',
  'params': {'alpha': 0.1, 'lambda': 0.3, 'gamma': 0.9},
  'overrides': {'max_decoder_steps': 2000}},
 'progress': [{'unit': 'sample',
   'i': 3826,
   'samplerate': '1/second',
   'start': 1740272567.8687654,
   'resources': {'rss_mb': 4602.8671875,
    'size_bytes': 113936,
    'vms_mb': 15286988800,
    'processes': 1,
    'num_threads': 76,
    'per_process_limit': 26281478400.0,
    'free_memory': 21822556000}}],
 'meta.device': ['GPU'],
 'tts_model': ['tts-tacotron2-ljspeech'],
 'vocoder_model': ['tts-hifigan-ljspeech'],
 'chunk_length': range(50, 500, 50),
 'batch_size': (1, 2, 3, 5, 10, 20, 30, 50, 70, 100, 200)}

# Trash

## GPU benchmarking

In [ ]:
import torch
#import torchvision.models as models
from torchaudio.pipelines import Tacotron2TTSBundle 
from torch.profiler import profile, record_function, ProfilerActivity

In [ ]:
# model = models.hubert_base()
# inputs = torch.randn(5, 224)

# with profile(activities=[ProfilerActivity.CPU],
#         profile_memory=True, record_shapes=True) as prof:
#     model(inputs)

# print(prof.key_averages().table(sort_by="self_cpu_memory_usage", row_limit=10))

In [ ]:
ttcp = narrator.profiles['tacotron']

In [ ]:
tbl = ttcp.key_averages().table(sort_by="self_cpu_memory_usage", row_limit=20)
tbl

In [ ]:
eve = ttcp.events()

In [ ]:
eve1000 = eve[1000]

In [ ]:
dir(eve1000)

In [ ]:
eve1000.time_range.start

In [ ]:
pd.DataFrame(eve)

In [ ]:
eve1000.__dict__

In [ ]:
ka = ttcp.key_averages()

In [ ]:
type(ka)

In [ ]:
len(ka)

In [ ]:
ka0 = ka[0]
ka0

In [ ]:
dir(ka0)

In [ ]:
type(ka0.key)

In [ ]:
ttcp.export_memory_timeline.__dir__()

In [ ]:
type(ttcp.export_memory_timeline.__self__)

In [ ]:
ttcp.export_memory_timeline("CPU_tacotron.raw.json.gz")

In [ ]:
vcdp = narrator.profiles['vocoder']

In [ ]:
print(vcdp.key_averages().table(sort_by="self_cpu_memory_usage", row_limit=10))

# End